name: Hello world action
 
on:
  pull_request:
    branches: [ "main" ]
 
jobs:
  log_greeting:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    steps:
    - uses: actions/checkout@v3
    - name: Environment setting
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_SHA }}
    - name: Print pull request details
      run: |
         echo "Hello World at $( date +"%d/%M/%Y" )";
         echo "Author: $PR_AUTHOR";
         echo "Last commit: $(git show -s --format=%s)";
         echo "Changes"
          branch_name="${{ github.event.pull_request.head.ref }}"
          git checkout origin/"${branch_name}"
          git diff origin/main
      shell: bash
